# Configure a default setup of Home Assistant (frontend, api, etc)
homeassistant:
  customize: !include customize.yaml

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# logger:
#   default: critical
#   logs:
#     custom_components.miio_yeelink: debug

# Text to speech
tts:
  - platform: google_translate

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.31.44
  ip_ban_enabled: true
  login_attempts_threshold: 3

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
