esphome:
  name: esphome-test
  platform: ESP8266
  board: nodemcuv2
  esp8266_restore_from_flash: true

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "6017582ab3fc8fab5df14ad173d67c93"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Smart-Home Fallback Hotspot"
    password: "Hzng3F4B47uK"

captive_portal:

number:
  - platform: template
    name: "Valve1 Delay"
    id: valve1_delay
    initial_value: 360
    min_value: 0
    max_value: 999
    step: 1
    optimistic: true
    restore_value: true
  - platform: template
    name: "Valve2 Delay"
    id: valve2_delay
    initial_value: 360
    min_value: 0
    max_value: 999
    step: 1
    optimistic: true
    restore_value: true
  - platform: template
    name: "Valve3 Delay"
    id: valve3_delay
    initial_value: 360
    min_value: 0
    max_value: 999
    step: 1
    optimistic: true
    restore_value: true
  - platform: template
    name: "Pump Delay"
    id: pump_delay
    initial_value: 360
    min_value: 0
    max_value: 999
    step: 1
    optimistic: true
    restore_value: true

switch:
  - platform: gpio
    pin: D5
    id: valve1
    name: "valve1"
    icon: "mdi:sprinkler-variant"
    on_turn_on:
      - delay: !lambda |-
          return id(valve1_delay).state * 1000;
      - switch.turn_off: valve1
  - platform: gpio
    pin: D6
    id: valve2
    name: "valve2"
    icon: "mdi:sprinkler-variant"
    on_turn_on:
      - delay: !lambda |-
          return id(valve2_delay).state * 1000;
      - switch.turn_off: valve2
  - platform: gpio
    pin: D7
    id: valve3
    name: "valve3"
    icon: "mdi:sprinkler-variant"
    on_turn_on:
      - delay: !lambda |-
          return id(valve3_delay).state * 1000;
      - switch.turn_off: valve3
  - platform: gpio
    pin: D8
    id: pump
    name: "pump"
    icon: "mdi:pump"
    on_turn_on:
      - delay: !lambda |-
          return id(pump_delay).state * 1000;
      - switch.turn_off: pump

binary_sensor:
  - platform: gpio
    pin: D1
    name: "valve1_button"
    on_press:
      then:
        - switch.toggle: valve1
  - platform: gpio
    pin: D2
    name: "valve2_button"
    on_press:
      then:
        - switch.toggle: valve2
  - platform: gpio
    pin: 9
    name: "valve3_button"
    on_press:
      then:
        - switch.toggle: valve3
  - platform: gpio
    pin: 10
    name: "pump_button"
    on_press:
      then:
        - switch.toggle: pump

sensor:
  - platform: dht
    pin: D4
    temperature:
      name: "Autowatering box temperature"
    humidity:
      name: "Autowatering box moisture"
    update_interval: 10s
