esphome:
  name: esphome-test
  platform: ESP8266
  board: nodemcuv2
  esp8266_restore_from_flash: true

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
- platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Smart-Home Fallback Hotspot"
    password: !secret fallback_wifi_password

captive_portal:

number:
  - platform: template
    name: "Valve1 Delay"
    id: valve1_delay
    initial_value: 360
    min_value: 0
    max_value: 999
    step: 1
    optimistic: true
    restore_value: true
  - platform: template
    name: "Valve2 Delay"
    id: valve2_delay
    initial_value: 360
    min_value: 0
    max_value: 999
    step: 1
    optimistic: true
    restore_value: true
  - platform: template
    name: "Valve3 Delay"
    id: valve3_delay
    initial_value: 360
    min_value: 0
    max_value: 999
    step: 1
    optimistic: true
    restore_value: true
  - platform: template
    name: "Pump Delay"
    id: pump_delay
    initial_value: 360
    min_value: 0
    max_value: 999
    step: 1
    optimistic: true
    restore_value: true

script:
  - id: valve1_delay_off
    mode: restart
    then:
      - delay: !lambda |-
          return id(valve1_delay).state * 1000;
      - switch.turn_off: valve1
  - id: valve2_delay_off
    mode: restart
    then:
      - delay: !lambda |-
          return id(valve2_delay).state * 1000;
      - switch.turn_off: valve2
  - id: valve3_delay_off
    mode: restart
    then:
      - delay: !lambda |-
          return id(valve3_delay).state * 1000;
      - switch.turn_off: valve3
  - id: pump_delay_off
    mode: restart
    then:
      - delay: !lambda |-
          return id(pump_delay).state * 1000;
      - switch.turn_off: pump

switch:
  - platform: gpio
    pin: D5
    id: valve1
    name: "valve1"
    icon: "mdi:sprinkler-variant"
    on_turn_on:
      - script.execute: valve1_delay_off
  - platform: gpio
    pin: D6
    id: valve2
    name: "valve2"
    icon: "mdi:sprinkler-variant"
    on_turn_on:
      - script.execute: valve2_delay_off
  - platform: gpio
    pin: D7
    id: valve3
    name: "valve3"
    icon: "mdi:sprinkler-variant"
    on_turn_on:
      - script.execute: valve3_delay_off
  - platform: gpio
    pin: D8
    id: pump
    name: "pump"
    icon: "mdi:pump"
    on_turn_on:
      - script.execute: pump_delay_off

binary_sensor:
  - platform: gpio
    pin: D1
    name: "valve1_button"
    on_press:
      then:
        - switch.toggle: valve1
  - platform: gpio
    pin: D2
    name: "valve2_button"
    on_press:
      then:
        - switch.toggle: valve2
  - platform: gpio
    pin: 9
    name: "valve3_button"
    on_press:
      then:
        - switch.toggle: valve3
  - platform: gpio
    pin: 10
    name: "pump_button"
    on_press:
      then:
        - switch.toggle: pump

sensor:
  - platform: dht
    pin: D4
    temperature:
      name: "Autowatering box temperature"
    humidity:
      name: "Autowatering box moisture"
    update_interval: 10s
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
  - platform: uptime
    name: Uptime Sensor
    id: uptime_sensor
    update_interval: 60s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? String(days) + "d " : "") +
                (hours ? String(hours) + "h " : "") +
                (minutes ? String(minutes) + "m " : "") +
                (String(seconds) + "s")
              ).c_str();

text_sensor:
  - platform: template
    name: Uptime Human Readable
    id: uptime_human
    icon: mdi:clock-start
